#!/usr/bin/env python3
"""Generates champs.json and the embedded DATA block in champs.star.

Source of truth for championship results. Team abbreviations are ESPN codes
for the *current* franchise (relocated teams map to their present-day
location). An empty abbreviation means the franchise folded and has no
present-day logo.

Usage: python3 apps/champs/build_data.py
"""

import json
import os
import re

# (year, title, winner_abbr, winner, loser_abbr, loser, score)
NFL = [
    (1967, "Super Bowl I", "GB", "Packers", "KC", "Chiefs", "35-10"),
    (1968, "Super Bowl II", "GB", "Packers", "LV", "Oakland Raiders", "33-14"),
    (1969, "Super Bowl III", "NYJ", "Jets", "IND", "Baltimore Colts", "16-7"),
    (1970, "Super Bowl IV", "KC", "Chiefs", "MIN", "Vikings", "23-7"),
    (1971, "Super Bowl V", "IND", "Baltimore Colts", "DAL", "Cowboys", "16-13"),
    (1972, "Super Bowl VI", "DAL", "Cowboys", "MIA", "Dolphins", "24-3"),
    (1973, "Super Bowl VII", "MIA", "Dolphins", "WSH", "Redskins", "14-7"),
    (1974, "Super Bowl VIII", "MIA", "Dolphins", "MIN", "Vikings", "24-7"),
    (1975, "Super Bowl IX", "PIT", "Steelers", "MIN", "Vikings", "16-6"),
    (1976, "Super Bowl X", "PIT", "Steelers", "DAL", "Cowboys", "21-17"),
    (1977, "Super Bowl XI", "LV", "Oakland Raiders", "MIN", "Vikings", "32-14"),
    (1978, "Super Bowl XII", "DAL", "Cowboys", "DEN", "Broncos", "27-10"),
    (1979, "Super Bowl XIII", "PIT", "Steelers", "DAL", "Cowboys", "35-31"),
    (1980, "Super Bowl XIV", "PIT", "Steelers", "LAR", "Rams", "31-19"),
    (1981, "Super Bowl XV", "LV", "Oakland Raiders", "PHI", "Eagles", "27-10"),
    (1982, "Super Bowl XVI", "SF", "49ers", "CIN", "Bengals", "26-21"),
    (1983, "Super Bowl XVII", "WSH", "Redskins", "MIA", "Dolphins", "27-17"),
    (1984, "Super Bowl XVIII", "LV", "L.A. Raiders", "WSH", "Redskins", "38-9"),
    (1985, "Super Bowl XIX", "SF", "49ers", "MIA", "Dolphins", "38-16"),
    (1986, "Super Bowl XX", "CHI", "Bears", "NE", "Patriots", "46-10"),
    (1987, "Super Bowl XXI", "NYG", "Giants", "DEN", "Broncos", "39-20"),
    (1988, "Super Bowl XXII", "WSH", "Redskins", "DEN", "Broncos", "42-10"),
    (1989, "Super Bowl XXIII", "SF", "49ers", "CIN", "Bengals", "20-16"),
    (1990, "Super Bowl XXIV", "SF", "49ers", "DEN", "Broncos", "55-10"),
    (1991, "Super Bowl XXV", "NYG", "Giants", "BUF", "Bills", "20-19"),
    (1992, "Super Bowl XXVI", "WSH", "Redskins", "BUF", "Bills", "37-24"),
    (1993, "Super Bowl XXVII", "DAL", "Cowboys", "BUF", "Bills", "52-17"),
    (1994, "Super Bowl XXVIII", "DAL", "Cowboys", "BUF", "Bills", "30-13"),
    (1995, "Super Bowl XXIX", "SF", "49ers", "LAC", "San Diego Chargers", "49-26"),
    (1996, "Super Bowl XXX", "DAL", "Cowboys", "PIT", "Steelers", "27-17"),
    (1997, "Super Bowl XXXI", "GB", "Packers", "NE", "Patriots", "35-21"),
    (1998, "Super Bowl XXXII", "DEN", "Broncos", "GB", "Packers", "31-24"),
    (1999, "Super Bowl XXXIII", "DEN", "Broncos", "ATL", "Falcons", "34-19"),
    (2000, "Super Bowl XXXIV", "LAR", "St. Louis Rams", "TEN", "Titans", "23-16"),
    (2001, "Super Bowl XXXV", "BAL", "Ravens", "NYG", "Giants", "34-7"),
    (2002, "Super Bowl XXXVI", "NE", "Patriots", "LAR", "St. Louis Rams", "20-17"),
    (2003, "Super Bowl XXXVII", "TB", "Buccaneers", "LV", "Oakland Raiders", "48-21"),
    (2004, "Super Bowl XXXVIII", "NE", "Patriots", "CAR", "Panthers", "32-29"),
    (2005, "Super Bowl XXXIX", "NE", "Patriots", "PHI", "Eagles", "24-21"),
    (2006, "Super Bowl XL", "PIT", "Steelers", "SEA", "Seahawks", "21-10"),
    (2007, "Super Bowl XLI", "IND", "Colts", "CHI", "Bears", "29-17"),
    (2008, "Super Bowl XLII", "NYG", "Giants", "NE", "Patriots", "17-14"),
    (2009, "Super Bowl XLIII", "PIT", "Steelers", "ARI", "Cardinals", "27-23"),
    (2010, "Super Bowl XLIV", "NO", "Saints", "IND", "Colts", "31-17"),
    (2011, "Super Bowl XLV", "GB", "Packers", "PIT", "Steelers", "31-25"),
    (2012, "Super Bowl XLVI", "NYG", "Giants", "NE", "Patriots", "21-17"),
    (2013, "Super Bowl XLVII", "BAL", "Ravens", "SF", "49ers", "34-31"),
    (2014, "Super Bowl XLVIII", "SEA", "Seahawks", "DEN", "Broncos", "43-8"),
    (2015, "Super Bowl XLIX", "NE", "Patriots", "SEA", "Seahawks", "28-24"),
    (2016, "Super Bowl 50", "DEN", "Broncos", "CAR", "Panthers", "24-10"),
    (2017, "Super Bowl LI", "NE", "Patriots", "ATL", "Falcons", "34-28"),
    (2018, "Super Bowl LII", "PHI", "Eagles", "NE", "Patriots", "41-33"),
    (2019, "Super Bowl LIII", "NE", "Patriots", "LAR", "Rams", "13-3"),
    (2020, "Super Bowl LIV", "KC", "Chiefs", "SF", "49ers", "31-20"),
    (2021, "Super Bowl LV", "TB", "Buccaneers", "KC", "Chiefs", "31-9"),
    (2022, "Super Bowl LVI", "LAR", "Rams", "CIN", "Bengals", "23-20"),
    (2023, "Super Bowl LVII", "KC", "Chiefs", "PHI", "Eagles", "38-35"),
    (2024, "Super Bowl LVIII", "KC", "Chiefs", "SF", "49ers", "25-22"),
    (2025, "Super Bowl LIX", "PHI", "Eagles", "KC", "Chiefs", "40-22"),
    (2026, "Super Bowl LX", "SEA", "Seahawks", "NE", "Patriots", "29-13"),
]

# Series results as games won (e.g. "4-2"). Ties in 1907/1912/1922 omitted.
MLB = [
    (1903, "World Series", "BOS", "Boston Americans", "PIT", "Pirates", "5-3"),
    (1905, "World Series", "SF", "N.Y. Giants", "ATH", "Phila. Athletics", "4-1"),
    (1906, "World Series", "CWS", "White Sox", "CHC", "Cubs", "4-2"),
    (1907, "World Series", "CHC", "Cubs", "DET", "Tigers", "4-0"),
    (1908, "World Series", "CHC", "Cubs", "DET", "Tigers", "4-1"),
    (1909, "World Series", "PIT", "Pirates", "DET", "Tigers", "4-3"),
    (1910, "World Series", "ATH", "Phila. Athletics", "CHC", "Cubs", "4-1"),
    (1911, "World Series", "ATH", "Phila. Athletics", "SF", "N.Y. Giants", "4-2"),
    (1912, "World Series", "BOS", "Red Sox", "SF", "N.Y. Giants", "4-3"),
    (1913, "World Series", "ATH", "Phila. Athletics", "SF", "N.Y. Giants", "4-1"),
    (1914, "World Series", "ATL", "Boston Braves", "ATH", "Phila. Athletics", "4-0"),
    (1915, "World Series", "BOS", "Red Sox", "PHI", "Phillies", "4-1"),
    (1916, "World Series", "BOS", "Red Sox", "LAD", "Brooklyn Robins", "4-1"),
    (1917, "World Series", "CWS", "White Sox", "SF", "N.Y. Giants", "4-2"),
    (1918, "World Series", "BOS", "Red Sox", "CHC", "Cubs", "4-2"),
    (1919, "World Series", "CIN", "Reds", "CWS", "White Sox", "5-3"),
    (1920, "World Series", "CLE", "Indians", "LAD", "Brooklyn Robins", "5-2"),
    (1921, "World Series", "SF", "N.Y. Giants", "NYY", "Yankees", "5-3"),
    (1922, "World Series", "SF", "N.Y. Giants", "NYY", "Yankees", "4-0"),
    (1923, "World Series", "NYY", "Yankees", "SF", "N.Y. Giants", "4-2"),
    (1924, "World Series", "MIN", "Wash. Senators", "SF", "N.Y. Giants", "4-3"),
    (1925, "World Series", "PIT", "Pirates", "MIN", "Wash. Senators", "4-3"),
    (1926, "World Series", "STL", "Cardinals", "NYY", "Yankees", "4-3"),
    (1927, "World Series", "NYY", "Yankees", "PIT", "Pirates", "4-0"),
    (1928, "World Series", "NYY", "Yankees", "STL", "Cardinals", "4-0"),
    (1929, "World Series", "ATH", "Phila. Athletics", "CHC", "Cubs", "4-1"),
    (1930, "World Series", "ATH", "Phila. Athletics", "STL", "Cardinals", "4-2"),
    (1931, "World Series", "STL", "Cardinals", "ATH", "Phila. Athletics", "4-3"),
    (1932, "World Series", "NYY", "Yankees", "CHC", "Cubs", "4-0"),
    (1933, "World Series", "SF", "N.Y. Giants", "MIN", "Wash. Senators", "4-1"),
    (1934, "World Series", "STL", "Cardinals", "DET", "Tigers", "4-3"),
    (1935, "World Series", "DET", "Tigers", "CHC", "Cubs", "4-2"),
    (1936, "World Series", "NYY", "Yankees", "SF", "N.Y. Giants", "4-2"),
    (1937, "World Series", "NYY", "Yankees", "SF", "N.Y. Giants", "4-1"),
    (1938, "World Series", "NYY", "Yankees", "CHC", "Cubs", "4-0"),
    (1939, "World Series", "NYY", "Yankees", "CIN", "Reds", "4-0"),
    (1940, "World Series", "CIN", "Reds", "DET", "Tigers", "4-3"),
    (1941, "World Series", "NYY", "Yankees", "LAD", "Brooklyn Dodgers", "4-1"),
    (1942, "World Series", "STL", "Cardinals", "NYY", "Yankees", "4-1"),
    (1943, "World Series", "NYY", "Yankees", "STL", "Cardinals", "4-1"),
    (1944, "World Series", "STL", "Cardinals", "BAL", "St. Louis Browns", "4-2"),
    (1945, "World Series", "DET", "Tigers", "CHC", "Cubs", "4-3"),
    (1946, "World Series", "STL", "Cardinals", "BOS", "Red Sox", "4-3"),
    (1947, "World Series", "NYY", "Yankees", "LAD", "Brooklyn Dodgers", "4-3"),
    (1948, "World Series", "CLE", "Indians", "ATL", "Boston Braves", "4-2"),
    (1949, "World Series", "NYY", "Yankees", "LAD", "Brooklyn Dodgers", "4-1"),
    (1950, "World Series", "NYY", "Yankees", "PHI", "Phillies", "4-0"),
    (1951, "World Series", "NYY", "Yankees", "SF", "N.Y. Giants", "4-2"),
    (1952, "World Series", "NYY", "Yankees", "LAD", "Brooklyn Dodgers", "4-3"),
    (1953, "World Series", "NYY", "Yankees", "LAD", "Brooklyn Dodgers", "4-2"),
    (1954, "World Series", "SF", "N.Y. Giants", "CLE", "Indians", "4-0"),
    (1955, "World Series", "LAD", "Brooklyn Dodgers", "NYY", "Yankees", "4-3"),
    (1956, "World Series", "NYY", "Yankees", "LAD", "Brooklyn Dodgers", "4-3"),
    (1957, "World Series", "ATL", "Milwaukee Braves", "NYY", "Yankees", "4-3"),
    (1958, "World Series", "NYY", "Yankees", "ATL", "Milwaukee Braves", "4-3"),
    (1959, "World Series", "LAD", "Dodgers", "CWS", "White Sox", "4-2"),
    (1960, "World Series", "PIT", "Pirates", "NYY", "Yankees", "4-3"),
    (1961, "World Series", "NYY", "Yankees", "CIN", "Reds", "4-1"),
    (1962, "World Series", "NYY", "Yankees", "SF", "Giants", "4-3"),
    (1963, "World Series", "LAD", "Dodgers", "NYY", "Yankees", "4-0"),
    (1964, "World Series", "STL", "Cardinals", "NYY", "Yankees", "4-3"),
    (1965, "World Series", "LAD", "Dodgers", "MIN", "Twins", "4-3"),
    (1966, "World Series", "BAL", "Orioles", "LAD", "Dodgers", "4-0"),
    (1967, "World Series", "STL", "Cardinals", "BOS", "Red Sox", "4-3"),
    (1968, "World Series", "DET", "Tigers", "STL", "Cardinals", "4-3"),
    (1969, "World Series", "NYM", "Mets", "BAL", "Orioles", "4-1"),
    (1970, "World Series", "BAL", "Orioles", "CIN", "Reds", "4-1"),
    (1971, "World Series", "PIT", "Pirates", "BAL", "Orioles", "4-3"),
    (1972, "World Series", "ATH", "Oakland Athletics", "CIN", "Reds", "4-3"),
    (1973, "World Series", "ATH", "Oakland Athletics", "NYM", "Mets", "4-3"),
    (1974, "World Series", "ATH", "Oakland Athletics", "LAD", "Dodgers", "4-1"),
    (1975, "World Series", "CIN", "Reds", "BOS", "Red Sox", "4-3"),
    (1976, "World Series", "CIN", "Reds", "NYY", "Yankees", "4-0"),
    (1977, "World Series", "NYY", "Yankees", "LAD", "Dodgers", "4-2"),
    (1978, "World Series", "NYY", "Yankees", "LAD", "Dodgers", "4-2"),
    (1979, "World Series", "PIT", "Pirates", "BAL", "Orioles", "4-3"),
    (1980, "World Series", "PHI", "Phillies", "KC", "Royals", "4-2"),
    (1981, "World Series", "LAD", "Dodgers", "NYY", "Yankees", "4-2"),
    (1982, "World Series", "STL", "Cardinals", "MIL", "Brewers", "4-3"),
    (1983, "World Series", "BAL", "Orioles", "PHI", "Phillies", "4-1"),
    (1984, "World Series", "DET", "Tigers", "SD", "Padres", "4-1"),
    (1985, "World Series", "KC", "Royals", "STL", "Cardinals", "4-3"),
    (1986, "World Series", "NYM", "Mets", "BOS", "Red Sox", "4-3"),
    (1987, "World Series", "MIN", "Twins", "STL", "Cardinals", "4-3"),
    (1988, "World Series", "LAD", "Dodgers", "ATH", "Oakland Athletics", "4-1"),
    (1989, "World Series", "ATH", "Oakland Athletics", "SF", "Giants", "4-0"),
    (1990, "World Series", "CIN", "Reds", "ATH", "Oakland Athletics", "4-0"),
    (1991, "World Series", "MIN", "Twins", "ATL", "Braves", "4-3"),
    (1992, "World Series", "TOR", "Blue Jays", "ATL", "Braves", "4-2"),
    (1993, "World Series", "TOR", "Blue Jays", "PHI", "Phillies", "4-2"),
    (1995, "World Series", "ATL", "Braves", "CLE", "Indians", "4-2"),
    (1996, "World Series", "NYY", "Yankees", "ATL", "Braves", "4-2"),
    (1997, "World Series", "MIA", "Florida Marlins", "CLE", "Indians", "4-3"),
    (1998, "World Series", "NYY", "Yankees", "SD", "Padres", "4-0"),
    (1999, "World Series", "NYY", "Yankees", "ATL", "Braves", "4-0"),
    (2000, "World Series", "NYY", "Yankees", "NYM", "Mets", "4-1"),
    (2001, "World Series", "ARI", "Diamondbacks", "NYY", "Yankees", "4-3"),
    (2002, "World Series", "LAA", "Anaheim Angels", "SF", "Giants", "4-3"),
    (2003, "World Series", "MIA", "Florida Marlins", "NYY", "Yankees", "4-2"),
    (2004, "World Series", "BOS", "Red Sox", "STL", "Cardinals", "4-0"),
    (2005, "World Series", "CWS", "White Sox", "HOU", "Astros", "4-0"),
    (2006, "World Series", "STL", "Cardinals", "DET", "Tigers", "4-1"),
    (2007, "World Series", "BOS", "Red Sox", "COL", "Rockies", "4-0"),
    (2008, "World Series", "PHI", "Phillies", "TB", "Rays", "4-1"),
    (2009, "World Series", "NYY", "Yankees", "PHI", "Phillies", "4-2"),
    (2010, "World Series", "SF", "Giants", "TEX", "Rangers", "4-1"),
    (2011, "World Series", "STL", "Cardinals", "TEX", "Rangers", "4-3"),
    (2012, "World Series", "SF", "Giants", "DET", "Tigers", "4-0"),
    (2013, "World Series", "BOS", "Red Sox", "STL", "Cardinals", "4-2"),
    (2014, "World Series", "SF", "Giants", "KC", "Royals", "4-3"),
    (2015, "World Series", "KC", "Royals", "NYM", "Mets", "4-1"),
    (2016, "World Series", "CHC", "Cubs", "CLE", "Indians", "4-3"),
    (2017, "World Series", "HOU", "Astros", "LAD", "Dodgers", "4-3"),
    (2018, "World Series", "BOS", "Red Sox", "LAD", "Dodgers", "4-1"),
    (2019, "World Series", "WSH", "Nationals", "HOU", "Astros", "4-3"),
    (2020, "World Series", "LAD", "Dodgers", "TB", "Rays", "4-2"),
    (2021, "World Series", "ATL", "Braves", "HOU", "Astros", "4-2"),
    (2022, "World Series", "HOU", "Astros", "PHI", "Phillies", "4-2"),
    (2023, "World Series", "TEX", "Rangers", "ARI", "Diamondbacks", "4-1"),
    (2024, "World Series", "LAD", "Dodgers", "NYY", "Yankees", "4-1"),
    (2025, "World Series", "LAD", "Dodgers", "TOR", "Blue Jays", "4-3"),
]

# 1947-1949 were BAA Finals (counted by the NBA as its own history).
NBA = [
    (1947, "BAA Finals", "GS", "Phila. Warriors", "", "Chicago Stags", "4-1"),
    (1948, "BAA Finals", "", "Baltimore Bullets", "GS", "Phila. Warriors", "4-2"),
    (1949, "BAA Finals", "LAL", "Mpls. Lakers", "", "Wash. Capitols", "4-2"),
    (1950, "NBA Finals", "LAL", "Mpls. Lakers", "PHI", "Syracuse Nationals", "4-2"),
    (1951, "NBA Finals", "SAC", "Rochester Royals", "NY", "Knicks", "4-3"),
    (1952, "NBA Finals", "LAL", "Mpls. Lakers", "NY", "Knicks", "4-3"),
    (1953, "NBA Finals", "LAL", "Mpls. Lakers", "NY", "Knicks", "4-1"),
    (1954, "NBA Finals", "LAL", "Mpls. Lakers", "PHI", "Syracuse Nationals", "4-3"),
    (1955, "NBA Finals", "PHI", "Syracuse Nationals", "DET", "Ft. Wayne Pistons", "4-3"),
    (1956, "NBA Finals", "GS", "Phila. Warriors", "DET", "Ft. Wayne Pistons", "4-1"),
    (1957, "NBA Finals", "BOS", "Celtics", "ATL", "St. Louis Hawks", "4-3"),
    (1958, "NBA Finals", "ATL", "St. Louis Hawks", "BOS", "Celtics", "4-2"),
    (1959, "NBA Finals", "BOS", "Celtics", "LAL", "Mpls. Lakers", "4-0"),
    (1960, "NBA Finals", "BOS", "Celtics", "ATL", "St. Louis Hawks", "4-3"),
    (1961, "NBA Finals", "BOS", "Celtics", "ATL", "St. Louis Hawks", "4-1"),
    (1962, "NBA Finals", "BOS", "Celtics", "LAL", "Lakers", "4-3"),
    (1963, "NBA Finals", "BOS", "Celtics", "LAL", "Lakers", "4-2"),
    (1964, "NBA Finals", "BOS", "Celtics", "GS", "S.F. Warriors", "4-1"),
    (1965, "NBA Finals", "BOS", "Celtics", "LAL", "Lakers", "4-1"),
    (1966, "NBA Finals", "BOS", "Celtics", "LAL", "Lakers", "4-3"),
    (1967, "NBA Finals", "PHI", "76ers", "GS", "S.F. Warriors", "4-2"),
    (1968, "NBA Finals", "BOS", "Celtics", "LAL", "Lakers", "4-2"),
    (1969, "NBA Finals", "BOS", "Celtics", "LAL", "Lakers", "4-3"),
    (1970, "NBA Finals", "NY", "Knicks", "LAL", "Lakers", "4-3"),
    (1971, "NBA Finals", "MIL", "Bucks", "WSH", "Baltimore Bullets", "4-0"),
    (1972, "NBA Finals", "LAL", "Lakers", "NY", "Knicks", "4-1"),
    (1973, "NBA Finals", "NY", "Knicks", "LAL", "Lakers", "4-1"),
    (1974, "NBA Finals", "BOS", "Celtics", "MIL", "Bucks", "4-3"),
    (1975, "NBA Finals", "GS", "Warriors", "WSH", "Wash. Bullets", "4-0"),
    (1976, "NBA Finals", "BOS", "Celtics", "PHX", "Suns", "4-2"),
    (1977, "NBA Finals", "POR", "Trail Blazers", "PHI", "76ers", "4-2"),
    (1978, "NBA Finals", "WSH", "Wash. Bullets", "OKC", "Seattle SuperSonics", "4-3"),
    (1979, "NBA Finals", "OKC", "Seattle SuperSonics", "WSH", "Wash. Bullets", "4-1"),
    (1980, "NBA Finals", "LAL", "Lakers", "PHI", "76ers", "4-2"),
    (1981, "NBA Finals", "BOS", "Celtics", "HOU", "Rockets", "4-2"),
    (1982, "NBA Finals", "LAL", "Lakers", "PHI", "76ers", "4-2"),
    (1983, "NBA Finals", "PHI", "76ers", "LAL", "Lakers", "4-0"),
    (1984, "NBA Finals", "BOS", "Celtics", "LAL", "Lakers", "4-3"),
    (1985, "NBA Finals", "LAL", "Lakers", "BOS", "Celtics", "4-2"),
    (1986, "NBA Finals", "BOS", "Celtics", "HOU", "Rockets", "4-2"),
    (1987, "NBA Finals", "LAL", "Lakers", "BOS", "Celtics", "4-2"),
    (1988, "NBA Finals", "LAL", "Lakers", "DET", "Pistons", "4-3"),
    (1989, "NBA Finals", "DET", "Pistons", "LAL", "Lakers", "4-0"),
    (1990, "NBA Finals", "DET", "Pistons", "POR", "Trail Blazers", "4-1"),
    (1991, "NBA Finals", "CHI", "Bulls", "LAL", "Lakers", "4-1"),
    (1992, "NBA Finals", "CHI", "Bulls", "POR", "Trail Blazers", "4-2"),
    (1993, "NBA Finals", "CHI", "Bulls", "PHX", "Suns", "4-2"),
    (1994, "NBA Finals", "HOU", "Rockets", "NY", "Knicks", "4-3"),
    (1995, "NBA Finals", "HOU", "Rockets", "ORL", "Magic", "4-0"),
    (1996, "NBA Finals", "CHI", "Bulls", "OKC", "Seattle SuperSonics", "4-2"),
    (1997, "NBA Finals", "CHI", "Bulls", "UTAH", "Jazz", "4-2"),
    (1998, "NBA Finals", "CHI", "Bulls", "UTAH", "Jazz", "4-2"),
    (1999, "NBA Finals", "SA", "Spurs", "NY", "Knicks", "4-1"),
    (2000, "NBA Finals", "LAL", "Lakers", "IND", "Pacers", "4-2"),
    (2001, "NBA Finals", "LAL", "Lakers", "PHI", "76ers", "4-1"),
    (2002, "NBA Finals", "LAL", "Lakers", "BKN", "New Jersey Nets", "4-0"),
    (2003, "NBA Finals", "SA", "Spurs", "BKN", "New Jersey Nets", "4-2"),
    (2004, "NBA Finals", "DET", "Pistons", "LAL", "Lakers", "4-1"),
    (2005, "NBA Finals", "SA", "Spurs", "DET", "Pistons", "4-3"),
    (2006, "NBA Finals", "MIA", "Heat", "DAL", "Mavericks", "4-2"),
    (2007, "NBA Finals", "SA", "Spurs", "CLE", "Cavaliers", "4-0"),
    (2008, "NBA Finals", "BOS", "Celtics", "LAL", "Lakers", "4-2"),
    (2009, "NBA Finals", "LAL", "Lakers", "ORL", "Magic", "4-1"),
    (2010, "NBA Finals", "LAL", "Lakers", "BOS", "Celtics", "4-3"),
    (2011, "NBA Finals", "DAL", "Mavericks", "MIA", "Heat", "4-2"),
    (2012, "NBA Finals", "MIA", "Heat", "OKC", "Thunder", "4-1"),
    (2013, "NBA Finals", "MIA", "Heat", "SA", "Spurs", "4-3"),
    (2014, "NBA Finals", "SA", "Spurs", "MIA", "Heat", "4-1"),
    (2015, "NBA Finals", "GS", "Warriors", "CLE", "Cavaliers", "4-2"),
    (2016, "NBA Finals", "CLE", "Cavaliers", "GS", "Warriors", "4-3"),
    (2017, "NBA Finals", "GS", "Warriors", "CLE", "Cavaliers", "4-1"),
    (2018, "NBA Finals", "GS", "Warriors", "CLE", "Cavaliers", "4-0"),
    (2019, "NBA Finals", "TOR", "Raptors", "GS", "Warriors", "4-2"),
    (2020, "NBA Finals", "LAL", "Lakers", "MIA", "Heat", "4-2"),
    (2021, "NBA Finals", "MIL", "Bucks", "PHX", "Suns", "4-2"),
    (2022, "NBA Finals", "GS", "Warriors", "BOS", "Celtics", "4-2"),
    (2023, "NBA Finals", "DEN", "Nuggets", "MIA", "Heat", "4-1"),
    (2024, "NBA Finals", "BOS", "Celtics", "DAL", "Mavericks", "4-1"),
    (2025, "NBA Finals", "OKC", "Thunder", "IND", "Pacers", "4-3"),
    (2026, "NBA Finals", "NY", "Knicks", "SA", "Spurs", "4-1"),
]


def rows(league, entries):
    return [
        {
            "league": league,
            "year": y,
            "title": t,
            "winner": w,
            "winner_abbr": wa,
            "loser": l,
            "loser_abbr": la,
            "score": s,
        }
        for (y, t, wa, w, la, l, s) in entries
    ]


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    data = rows("NFL", NFL) + rows("MLB", MLB) + rows("NBA", NBA)

    with open(os.path.join(here, "champs.json"), "w") as f:
        json.dump(data, f, indent=1)
        f.write("\n")

    # Compact one-row-per-line JSON embedded in the applet.
    lines = ",\n".join(json.dumps(r, separators=(",", ":")) for r in data)
    block = "DATA_JSON = \"\"\"[\n" + lines + "\n]\"\"\"\n"

    star_path = os.path.join(here, "champs.star")
    with open(star_path) as f:
        src = f.read()
    new_src, n = re.subn(
        r'DATA_JSON = """\[.*?\]"""\n', lambda _: block, src, flags=re.S
    )
    if n != 1:
        raise SystemExit("DATA_JSON block not found in champs.star")
    with open(star_path, "w") as f:
        f.write(new_src)
    print("wrote %d championships" % len(data))


if __name__ == "__main__":
    main()
