# Copyright 2026 cptntrps
# SPDX-License-Identifier: Apache-2.0

"""Original short summaries of NHS pregnancy guidance, checked 2026-10-10.

Weeks are gestational weeks, as in the app's due-date calculation. These are
typical developmental stages, not observations of an individual baby. Each
language uses three manually wrapped lines of at most 15 ASCII characters for
the panel's 3x5 font. See DEVELOPMENT.md for the exact source for every week.
"""

# The factual basis for each joke: week -> (English lines, Portuguese lines).
FACTS = {
    4: (("BABY GROWS", "INSIDE A", "SAC WITH FLUID"),
        ("BEBE CRESCE", "NUMA BOLSA", "COM LIQUIDO")),
    5: (("BRAIN AND", "SPINAL CORD", "ARE FORMING"),
        ("CEREBRO E", "MEDULA ESTAO", "SE FORMANDO")),
    6: (("TINY ARM", "AND LEG BUDS", "ARE FORMING"),
        ("BRACOS E", "PERNAS COMECAM", "A SE FORMAR")),
    7: (("EYELIDS", "ARE STARTING", "TO DEVELOP"),
        ("AS PALPEBRAS", "COMECAM A", "SE FORMAR")),
    8: (("LITTLE ARMS", "AND LEGS ARE", "GETTING LONGER"),
        ("BRACOS E", "PERNAS ESTAO", "SE ALONGANDO")),
    9: (("TINY TASTE", "BUDS ARE", "DEVELOPING"),
        ("PAPILAS DO", "PALADAR ESTAO", "SE FORMANDO")),
    10: (("MILK TEETH", "ARE FORMING", "IN THE JAW"),
         ("DENTES DE LEITE", "SE FORMAM", "NA MANDIBULA")),
    11: (("FINGERS", "AND TOES ARE", "SEPARATING"),
         ("DEDOS DAS MAOS", "E DOS PES VAO", "SE SEPARANDO")),
    12: (("SKELETON", "IS HARDENING", "INTO BONE"),
         ("O ESQUELETO", "ENDURECE E", "FORMA OSSOS")),
    13: (("BABY MAY", "PRACTISE", "THUMB-SUCKING"),
         ("BEBE JA PODE", "TREINAR CHUPAR", "O POLEGAR")),
    14: (("KIDNEYS", "ARE MAKING", "URINE"),
         ("OS RINS", "JA PRODUZEM", "URINA")),
    15: (("EYEBROWS", "AND LASHES", "ARE DEVELOPING"),
         ("SOBRANCELHAS", "E CILIOS VAO", "SE FORMANDO")),
    16: (("HANDS CAN", "NOW FORM", "LITTLE FISTS"),
         ("BEBE JA PODE", "FECHAR AS MAOS", "EM PUNHOS")),
    17: (("BABY CAN", "OPEN AND CLOSE", "THEIR MOUTH"),
         ("BEBE JA PODE", "ABRIR E FECHAR", "A BOCA")),
    18: (("SUCKING AND", "SWALLOWING", "ARE DEVELOPING"),
         ("REFLEXOS DE", "SUGAR E ENGOLIR", "SE DESENVOLVEM")),
    19: (("ADULT TEETH", "BEGIN TO FORM", "IN THE JAW"),
         ("DENTES", "PERMANENTES", "SE FORMAM")),
    20: (("WAXY VERNIX", "NOW COVERS", "BABY'S SKIN"),
         ("A PELE GANHA", "UMA CAMADA", "DE VERNIX")),
    21: (("BABY CAN HEAR", "VOICES FROM", "OUTSIDE"),
         ("BEBE JA OUVE", "VOZES DE FORA", "DO UTERO")),
    22: (("LUNGS ARE", "DEVELOPING FOR", "BREATHING"),
         ("PULMOES SE", "DESENVOLVEM", "PARA RESPIRAR")),
    23: (("ARMS AND LEGS", "ARE NOW IN", "PROPORTION"),
         ("BRACOS E PERNAS", "JA ESTAO", "PROPORCIONAIS")),
    24: (("BABY'S BODY", "HAS BALANCED", "PROPORTIONS"),
         ("O CORPO ESTA", "COM AS PARTES", "PROPORCIONAIS")),
    25: (("BABY MAY", "HAVE LITTLE", "HICCUPS"),
         ("BEBE PODE", "TER PEQUENOS", "SOLUCOS")),
    26: (("EYES ARE", "STARTING", "TO OPEN"),
         ("OS OLHOS", "COMECAM", "A SE ABRIR")),
    27: (("FAT IS", "FILLING OUT", "SKIN FOLDS"),
         ("A GORDURA VAI", "PREENCHENDO", "DOBRAS DA PELE")),
    28: (("BABY'S HEART", "BEATS FASTER", "THAN YOURS"),
         ("CORACAO BATE", "MAIS RAPIDO", "QUE O SEU")),
    29: (("ORGANS", "CONTINUE", "TO MATURE"),
         ("OS ORGAOS", "CONTINUAM A", "AMADURECER")),
    30: (("EYES CAN", "NOW BEGIN", "TO FOCUS"),
         ("OS OLHOS", "JA CONSEGUEM", "FOCALIZAR")),
    31: (("BABY BEGINS", "TO RECOGNISE", "VOICES"),
         ("BEBE COMECA", "A RECONHECER", "VOZES")),
    32: (("BABY IS", "PUTTING ON", "MORE WEIGHT"),
         ("BEBE ESTA", "GANHANDO", "MAIS PESO")),
    33: (("BONES HARDEN", "WHILE THE SKULL", "STAYS SOFT"),
         ("OSSOS ENDURECEM", "MAS O CRANIO", "SEGUE MACIO")),
    34: (("LITTLE LEGS", "CURL TOWARDS", "THE CHEST"),
         ("PERNINHAS", "SE DOBRAM JUNTO", "AO PEITO")),
    35: (("ADDING FAT", "HELPS BABY", "KEEP WARM"),
         ("GANHAR GORDURA", "AJUDA A MANTER", "BEBE AQUECIDO")),
    36: (("BABY CAN", "SUCK AND", "DIGEST MILK"),
         ("BEBE JA PODE", "SUGAR E", "DIGERIR LEITE")),
    37: (("BABY TRIES", "DIFFERENT", "EXPRESSIONS"),
         ("BEBE FAZ", "DIFERENTES", "EXPRESSOES")),
    38: (("SOFT BODY", "HAIR IS", "SHEDDING"),
         ("A PENUGEM", "DO CORPO VAI", "DESAPARECENDO")),
    39: (("A STRONGER", "SKIN LAYER", "IS DEVELOPING"),
         ("A PELE GANHA", "UMA CAMADA", "MAIS RESISTENTE")),
    40: (("MOVEMENT", "CONTINUES", "UNTIL BIRTH"),
         ("MOVIMENTOS", "CONTINUAM ATE", "O NASCIMENTO")),
}


# Panel copy: playful wording, grounded in the corresponding FACTS and source.
DEVELOPMENT = {
    4: (("FIRST HOME:", "A COZY SAC", "FULL OF FLUID"),
        ("PRIMEIRO LAR:", "UMA BOLSA", "COM LIQUIDO")),
    5: (("BRAIN", "CONSTRUCTION", "CREW: ON DUTY"),
        ("OBRA A TODO", "VAPOR: CEREBRO", "EM CONSTRUCAO")),
    6: (("ARMS & LEGS:", "SOME ASSEMBLY", "IN PROGRESS"),
        ("BRACOS E", "PERNAS: OBRA", "EM ANDAMENTO")),
    7: (("EYELIDS", "UNDER", "CONSTRUCTION"),
        ("PALPEBRAS", "EM OBRAS", "AGUARDE...")),
    8: (("ARM AND LEG", "EXTENSIONS", "IN PROGRESS"),
        ("BRACOS E", "PERNAS GANHAM", "UMA ESTICADA")),
    9: (("TINY GOURMET:", "TASTE BUDS", "ARE FORMING"),
        ("MINI GOURMET:", "PAPILAS DO", "PALADAR SURGEM")),
    10: (("NO BITING YET", "BUT MILK TEETH", "ARE FORMING"),
         ("SEM MORDER!", "DENTES DE LEITE", "EM FORMACAO")),
    11: (("FINGERS & TOES", "ARE CLAIMING", "THEIR OWN SPACE"),
         ("DEDINHOS", "CONQUISTAM", "SEU ESPACO")),
    12: (("BONE BUILDING", "CREW IS", "CLOCKING IN"),
         ("EQUIPE DOS", "OSSOS ENTRA", "EM ACAO")),
    13: (("THUMB SUCKING:", "BABY MAY BE", "REHEARSING"),
         ("POLEGAR NA BOCA", "BEBE PODE", "ESTAR ENSAIANDO")),
    14: (("BABY'S FIRST", "PLUMBING JOB:", "MAKING PEE"),
         ("MINI RINS", "TRABALHANDO:", "FAZENDO XIXI")),
    15: (("BROWS & LASHES", "BEAUTY SALON", "NOW OPEN"),
         ("SOBRANCELHAS", "E CILIOS:", "SALAO ABERTO")),
    16: (("TINY FISTS", "YOUR LITTLE", "BOXER IS READY"),
         ("MAOZINHAS", "EM PUNHO:", "MINI BOXEADOR")),
    17: (("MOUTH OPENS", "MOUTH CLOSES", "SILENT KARAOKE"),
         ("ABRE A BOCA", "FECHA A BOCA", "KARAOKE MUDO")),
    18: (("SNACK SKILLS:", "SUCKING AND", "SWALLOWING"),
         ("SUGAR, ENGOLIR", "E REPETIR:", "BEBE TREINANDO")),
    19: (("ADULT TEETH", "START EARLY", "LONG-TERM PLANS"),
         ("DENTES DE", "ADULTO: BEBE", "PLANEJA LONGE")),
    20: (("BABY'S SKIN", "GETS A WAXY", "PROTECTIVE COAT"),
         ("PELE GANHA", "SEU CASACO", "DE VERNIX")),
    21: (("YOUR BABY CAN", "EAVESDROP", "ON YOU"),
         ("BEBE JA OUVE", "A CONVERSA", "AI FORA")),
    22: (("BREATHING", "REHEARSALS", "HAVE BEGUN"),
         ("ENSAIOS PARA", "RESPIRAR", "JA COMECARAM")),
    23: (("ARMS & LEGS", "FIND THEIR", "PERFECT FIT"),
         ("BRACOS E PERNAS", "ACHAM A", "MEDIDA CERTA")),
    24: (("MINI HUMAN", "PROPORTIONS", "CHECKED OFF"),
         ("MINI HUMANO", "PROPORCOES", "EM DIA")),
    25: (("TINY HICCUPS", "MAY JOIN THE", "WOMB PLAYLIST"),
         ("SOLUCOS PODEM", "ENTRAR NA", "TRILHA DO BEBE")),
    26: (("PEEKABOO:", "LITTLE EYES", "START TO OPEN"),
         ("ESPIADINHA:", "OS OLHOS", "COMECAM A ABRIR")),
    27: (("FILLING OUT", "THOSE WRINKLES", "WITH BABY FAT"),
         ("GORDURINHA", "PREENCHENDO", "AS DOBRINHAS")),
    28: (("HEARTBEAT", "REMIX: FASTER", "THAN YOURS"),
         ("RITMO ACELERADO", "MAIS RAPIDO", "QUE O SEU")),
    29: (("ORGANS ARE", "GETTING THEIR", "NEXT UPGRADE"),
         ("ORGAOS EM", "ATUALIZACAO:", "BEBE CRESCENDO")),
    30: (("FOCUS MODE", "BABY'S EYES", "UNLOCKED"),
         ("MODO FOCO", "ATIVADO", "NOS OLHINHOS")),
    31: (("YOUR VOICE", "IS JOINING", "THE VIP LIST"),
         ("SUA VOZ", "ENTROU NA", "LISTA VIP")),
    32: (("BABY'S TO-DO:", "GROW, GROW", "AND GROW"),
         ("TAREFA DO BEBE:", "CRESCER", "E ENGORDAR")),
    33: (("BONES FIRM UP", "SKULL KEEPS", "ITS SOFT SIDE"),
         ("OSSOS FIRMAM", "CRANIO MANTEM", "O LADO MACIO")),
    34: (("TINY YOGA", "LEGS TUCKED", "TO THE CHEST"),
         ("MINI IOGA:", "PERNAS JUNTO", "AO PEITO")),
    35: (("ADDING FAT", "FOR BABY'S", "OWN HEATING"),
         ("GORDURINHA", "PARA MANTER", "BEBE QUENTINHO")),
    36: (("PRACTISE SUCK", "GET READY FOR", "THE MILK MENU"),
         ("ENSAIANDO", "PARA O MENU", "DE LEITE")),
    37: (("FROWNS & GRINS", "BABY TRIES", "NEW FACES"),
         ("CARAS E BOCAS", "NOVOS ENSAIOS", "DO BEBE")),
    38: (("THE FUZZY", "BABY COAT", "IS SHEDDING"),
         ("CASACO", "FELPUDINHO", "SAINDO DE CENA")),
    39: (("SKIN UPGRADE", "A TOUGHER", "OUTER LAYER"),
         ("PELE NOVA:", "MAIS FORTE", "POR FORA")),
    40: (("STILL MOVING", "STILL GROOVING", "UNTIL BIRTH"),
         ("MEXE E REMEXE", "ATE O DIA", "DE NASCER")),
}


def source_url(week):
    trimester = "1st" if week <= 12 else "2nd" if week <= 27 else "3rd"
    return ("https://www.nhs.uk/best-start-in-life/pregnancy/"
            f"week-by-week-guide-to-pregnancy/{trimester}-trimester/week-{week}/")


SOURCES = {week: source_url(week) for week in DEVELOPMENT}
