# Copyright 2026 cptntrps
# SPDX-License-Identifier: Apache-2.0

"""Gen 1 comparisons and original, code-native 16x16 character sprites.

Heights checked against https://sg.portal-pokemon.com/pokedex/ on 2026-10-10.
Each number below links to /pokedex/NNNN/. Only the original Kanto forms are used.
This curated selection uses heights of 30, 40 and 50 cm. Diglett (20 cm) does
not fit the change from crown-rump to crown-heel measurements.
"""

# object: (national Pokedex number, height in cm, panel label)
POKEMON = {
    "squirtle": (7, 50, "SQUIRTLE"),
    "caterpie": (10, 30, "CATERPIE"),
    "weedle": (13, 30, "WEEDLE"),
    "pidgey": (16, 30, "PIDGEY"),
    "rattata": (19, 30, "RATTATA"),
    "spearow": (21, 30, "SPEAROW"),
    "pikachu": (25, 40, "PIKACHU"),
    "nidoranf": (29, 40, "NIDORAN F"),
    "nidoranm": (32, 50, "NIDORAN M"),
    "jigglypuff": (39, 50, "JIGGLYPUFF"),
    "oddish": (43, 50, "ODDISH"),
    "paras": (46, 30, "PARAS"),
    "meowth": (52, 40, "MEOWTH"),
    "mankey": (56, 50, "MANKEY"),
    "geodude": (74, 40, "GEODUDE"),
    "magnemite": (81, 30, "MAGNEMITE"),
    "shellder": (90, 30, "SHELLDER"),
    "krabby": (98, 40, "KRABBY"),
    "voltorb": (100, 50, "VOLTORB"),
    "horsea": (116, 40, "HORSEA"),
    "ditto": (132, 30, "DITTO"),
    "eevee": (133, 30, "EEVEE"),
    "omanyte": (138, 40, "OMANYTE"),
    "kabuto": (140, 50, "KABUTO"),
    "mew": (151, 40, "MEW"),
}


def sprite(rows, **palette):
    rows = rows.split()
    assert len(rows) == 16 and all(len(row) == 16 for row in rows), rows
    assert set("".join(rows)) <= set(palette) | {"."}
    return rows, {"o": "#382e46", **palette}


SPRITES = {
    "eevee": sprite("""
        ..oo......oo....
        .obbo....obbo...
        .obdbo..obdbo...
        .obddboobddbo...
        ..obbbbbbbbo....
        ..obhbbbbhbo....
        .obwebbbewbbo...
        .obwebbbewbbo...
        ..obbbdbbbbo....
        ...occcccco..oo.
        ..ocwccwcccoocwo
        ...ocwccwcoobcco
        ....obbbboobbbbo
        ...obbbbbbsbboo.
        ...obboobbboo...
        ...oooo.oooo....
    """, o="#483047", b="#bf8046", h="#dfa66a", d="#674238", s="#8d553c", c="#f4d5a0", w="#fff0c7", e="#292538"),
    "ditto": sprite("""
        ................
        ................
        ................
        ...ooo..........
        ..obbbbo..ooo...
        .obhbbbboobbbbo.
        .obhbbbbbbbbbo..
        .obbbbbbbbbbbbo.
        ..obbebbbbebbo..
        ..obbbbbbbbbbo..
        .obbbbbddbbbbbo.
        .obbbbbbbbbbbsso
        obbbbbbbbbbbbsso
        obbbboooobbbbsso
        .oooo....oooooo.
        ................
    """, o="#663c78", b="#c58de2", h="#ecc3f8", s="#9e69c5", e="#382944", d="#704281"),
    "mew": sprite("""
        ...oo....oo.....
        ..oppo..oppo....
        ..opppoopppo....
        ..ophppppppo....
        .opwpppppwppo...
        .opbepppebppo...
        ..oppppppppo....
        ...oppppppo.....
        ....oppppo......
        ...oppppppo...oo
        ..opoppppopo.opo
        ...ooppppooo.opo
        ....oppppo...opo
        ...ophophpo..opo
        ...oo..oo.opppo.
        ...........ooo..
    """, o="#74395f", p="#f3a6cc", h="#ffd8eb", w="#fff4f9", b="#62c6e9", e="#343253"),
    "squirtle": sprite("""
        ................
        .....oooooo.....
        ....obhhbbbo....
        ...obhhbbbbbo...
        ...owwbbbbwwo...
        ...owebbbbewo...
        ....obbbbbo.....
        .....obbbbo.....
        ...oobbccbsso...
        ..obobcccsssso..
        ...oobcdccsssso.
        .....bccdcssso..
        .oooobcccsssso..
        obbhoobcccsoo...
        .ooooobbooobbo..
        ......ooo.oooo..
    """, o="#314253", b="#69c6dd", h="#b1edf3", w="#faf3e8", e="#793e49", c="#f7d998", d="#c39b60", s="#ac713f"),
    "caterpie": sprite("""
        ....rr..rr......
        ....rroorr......
        .....oggo.......
        ....oggggo......
        ...oggwggwgo....
        ...oggeggego....
        ...ogggggggo....
        ....ogyyggo.....
        .....oyyyo......
        ....ogggggo.....
        ....ogygggo.....
        .....oggggo.....
        ..oo.ogyggo.....
        .oggoogggo......
        ..ogggggo.......
        ...ooooo........
    """, o="#344c35", g="#7bc849", y="#f6e786", r="#f07171", w="#fff8da", e="#303b33"),
    "weedle": sprite("""
        ......o.........
        .....owo........
        .....owo........
        ....ooooo.......
        ...obhhbbo......
        ..obbbbbboo.....
        ..obebbbebo.....
        ...obbppbo......
        ....opppo.......
        ....obbbo.......
        ...obhhbbo......
        ....opppo.......
        ....obbbo..oo...
        ...obhhbboowwo..
        ....obbbbbooo...
        .....ooooo......
    """, o="#5c4144", b="#d7ac65", h="#f3d394", p="#ef92b5", w="#f5f1dc", e="#352d36"),
    "pidgey": sprite("""
        ................
        ......oo........
        .....obbbo......
        ....obhbbbo.....
        ...obbcccbo.....
        ...obceccbo.....
        ....occqqo......
        .....occo.......
        ....obcccbo.....
        ...obbcccbo.....
        ..obbbccccbo....
        .obssbccccbo....
        ..obssbccbo.....
        ...oobbbboo.....
        .....qooq.......
        ....qq..qq......
    """, o="#4d3540", b="#b28455", h="#dfb87c", c="#f6ddaa", s="#806047", q="#f1a067", e="#2c2931"),
    "spearow": sprite("""
        ................
        .....o.o........
        ....obobo.......
        ...obbbbboo.....
        ...obwbbbbo.....
        ...obebbbbo.....
        ....obqqqqo.....
        ...oorcooo......
        ..orrrccco......
        .orrrrrccco.....
        orrrrsrccco.....
        .oorsscccco.....
        ...osscccbo.....
        ...oossbbo......
        .....qooq.......
        ....qq..qq......
    """, o="#4e343d", b="#a47650", r="#d77756", s="#885443", c="#f5d99c", q="#edb575", w="#fff3d5", e="#332835"),
    "rattata": sprite("""
        ................
        ...oo....oo.....
        ..obpo..opbo....
        ..obppoopbbo....
        ...obbbbbbo.....
        ..obwbbbwbbo....
        ..obebbbebbo....
        .ccobbnnbocc....
        ....obwwbo...oo.
        .....occo...obo.
        ....obbcco..obo.
        ...obbbccbo..obo
        ...obbbcccboobbo
        ....obbccbbboo..
        ...occooocco....
        ...ooo..ooo.....
    """, o="#48344e", b="#ab76ca", p="#eda2c0", c="#f3d9ab", w="#fff9e8", n="#f0a2b2", e="#bb435f"),
    "nidoranf": sprite("""
        ...oo....oo.....
        ..obpo..opbo....
        ..obppooppbo....
        ..obpbbbbpbo....
        ...obbobbbo.....
        ..obbbhbbbbo....
        ..obwbbbbwbo....
        ..obebbbbebo....
        ...obbbbbbo.....
        ...obbdbbbo.....
        ..obdbbbdbbo....
        .obbbbbbbbbbo...
        .obbdbbbdbbbo...
        ..obbboobbbo....
        ..owwo..owwo....
        ...oo....oo.....
    """, o="#3e405f", b="#8abfe4", h="#c1e5f5", p="#8490c1", d="#6571a6", w="#fff7e9", e="#bd526b"),
    "nidoranm": sprite("""
        ..oo......oo....
        .obpo....opbo...
        .obppo..oppbo...
        ..obpboobpbo....
        ...obbowbbo.....
        ..obbbowbbbo....
        ..obwbbbbwbo....
        ..obebbbbebo....
        ...obbbbbbo.....
        ...obbdbbbo.....
        ..obdbbbdbbo....
        .obbbbbbbbbbo...
        .obbdbbbdbbbo...
        ..obbboobbbo....
        ..owwo..owwo....
        ...oo....oo.....
    """, o="#533e65", b="#c089cf", p="#64bdaf", d="#9564af", w="#fcf1e8", e="#bb4667"),
    "oddish": sprite("""
        ....l...l.......
        ...lg..lgl......
        ...lgg.lgl......
        .ll.lgllgl.ll...
        .lgl.lggl.lgl...
        ..lgglggllgl....
        ...lggggggl.....
        ....oooooo......
        ...obhhbbbo.....
        ..obhhbbbbbo....
        ..obebbbebbo....
        ..obbbbbbbbo....
        ...obbrbbbo.....
        ....obbbbo......
        ...obboobbo.....
        ...ooo..ooo.....
    """, o="#343853", l="#33744b", g="#83cb58", b="#6585d0", h="#97b5ea", e="#e68b95", r="#c65a76"),
    "paras": sprite("""
        ................
        ...ooo..ooo.....
        ..orrroorrro....
        .orwrrrorwrro...
        .orrwrrorrrwo...
        ..orrroorrro....
        ...obboobbo.....
        ..obbbbbbbbo....
        .obwebbbwebbo...
        .obwebbbwebbo...
        ..obbbddbbbo....
        .obbobbbbobbo...
        obbo.oooo.obbo..
        .oo.ob..bo.oo...
        ...oo....oo.....
        ................
    """, o="#754437", b="#edaa62", r="#e77363", w="#ffedb4", e="#3f3636", d="#a65c49"),
    "meowth": sprite("""
        ...oo....oo.....
        ..odco..ocdo....
        ..odccyyccdo....
        ...occyycco.....
        ...occyycco.....
        ..occcccccco....
        ..ocecccceco....
        .ddoccnncodd....
        ..occcccccco....
        ...ooccccoo.....
        ....occco....oo.
        ...occcccoo.oddo
        ..ococcccodooddo
        ...ooccccooddoo.
        ....ococco......
        ...oddo.oddo....
    """, o="#564149", c="#f4dcb2", d="#ab805a", y="#f6c84b", e="#37313b", n="#d59c85"),
    "mankey": sprite("""
        ....o....o......
        ...ocooocco.....
        ..occcccccco....
        .odccccccccdo...
        .odccecccecdo...
        ..occppppcco....
        ..occpddpcco....
        ...ocppppco.....
        ..occcccccco....
        .ocdccccccdco...
        .odocccccodo..oo
        ..oocccccoo..odo
        ....occcco..oddo
        ...oddoooddoddo.
        ...odd...odddo..
        ....oo....ooo...
    """, o="#55444a", c="#e8d3aa", d="#a88a65", p="#efb0aa", e="#54323a"),
    "geodude": sprite("""
        ................
        ................
        .....oooooo.....
        ....oshhhsso....
        ...oshhhhhssso..
        ...ohwsssswho...
        .ooosehsshesoo..
        ossosssssssosso.
        oshosssssssoshso
        oshossoooososhso
        oshosssssssoshso
        .ossoossssossoo.
        ..ooo.oooo.ooo..
        ................
        ................
        ................
    """, o="#454050", s="#9a969e", h="#c8c3c7", w="#f6f0e9", e="#373342"),
    "magnemite": sprite("""
        ................
        ......oooo......
        ......ohho......
        .......oo.......
        .....oooooo.....
        .rr.ossshhso.bb.
        .rr.oswwwwso.bb.
        .ss.oswewwso.ss.
        .ssoswwwwwsoss..
        .ssssssssssss...
        ..oossssssoo....
        ...ooshhssoo....
        ....oooooo......
        ....oho.oho.....
        ....ooo.ooo.....
        ................
    """, o="#364454", s="#9aafba", h="#d6e4e4", w="#fbf5e9", e="#323346", r="#e96871", b="#629fde"),
    "shellder": sprite("""
        ................
        ...o..oo..o.....
        ..opooppoppo....
        .oppphpphpppo...
        .ophpppppphpo...
        ..opphpphppo....
        .oppppppppppo...
        .opooooooooopo..
        ..owwddddwwo....
        ..oweddddewo....
        ..oddddddddo....
        ...odttttdo.....
        ..oppttttppo....
        ...opttttpo.....
        ....otttto......
        .....oooo.......
    """, o="#483859", p="#9c8bd2", h="#c7b5ea", d="#585074", w="#fff4dd", e="#312f43", t="#f0a0bc"),
    "krabby": sprite("""
        ................
        .rr..rr.........
        orroorro....rrr.
        orrrrrro...orrro
        .orrrro....orrro
        ..orro......oro.
        ...oro..e.e.oro.
        ...orroowooworo.
        ....orrrrrrro...
        ...orrrhhrrrro..
        ..orrrhhhhrrrro.
        ...occcccccco...
        ..orocccccoro...
        .oro.ooooo.oro..
        .oo.........oo..
        ................
    """, o="#71473e", r="#ee9663", h="#ffb77d", c="#f4dfb6", w="#fff5e0", e="#34333c"),
    "voltorb": sprite("""
        ................
        .....oooooo.....
        ...oorrrrrroo...
        ..orhhrrrrrrro..
        .orhhrrrrrrrrro.
        .orhrrrrrrrrrro.
        orrrrrrrrrrrrrro
        orrwerrrrrewrrro
        orrrwwrrrrwwrrro
        occcccccccccccco
        .occcccccccccco.
        .ochhcccccccsso.
        ..ochhhccccsso..
        ...oocccccsoo...
        .....oooooo.....
        ................
    """, o="#4c3545", r="#e45c65", h="#fff2e3", c="#e6ded7", s="#a6a9b7", w="#fffaf1", e="#3f3549"),
    "horsea": sprite("""
        ................
        ......oo........
        .....obbo.......
        ....obhbbo......
        ...obhhbbbo.....
        ...obwbbbbbboo..
        ...obebbbbbbbbo.
        ....obbbbboooo..
        .....obcco......
        ....obccco......
        ...oybccco......
        ....ybccco......
        .....obcco.oo...
        ......obboobbo..
        .......obbbbo...
        ........oooo....
    """, o="#344c68", b="#69bfdc", h="#abe6f0", w="#fff4e0", e="#be587b", c="#f1deb4", y="#e4b963"),
    "omanyte": sprite("""
        ................
        .....oooooo.....
        ...ooccccccoo...
        ..occhhhccccco..
        .occhccooocccco.
        .occccoococccco.
        .occcocccocccco.
        .occccoooccccco.
        ..occcccccccco..
        ...oobbbbbboo...
        ..obwwbbwwbbo...
        ..obwebbwebbo...
        ...obbbbbbo.....
        ..obobbbbobo....
        .obboobboobbo...
        ..oo..oo..oo....
    """, o="#4b4658", c="#e5ce99", h="#fff0c2", b="#7bc8e2", w="#fff9ed", e="#344353"),
    "kabuto": sprite("""
        ................
        .....oooooo.....
        ...oobbbbbboo...
        ..obhhbbbbbbbo..
        .obhhbbbbbbbsbo.
        .obhbbbbbbbbsbo.
        obbbbbbbsbbbsbbo
        obbbbbbbbsbbsbbo
        obbbbbbbbbsssbbo
        .obbbbbbbbbbboo.
        ..oodddddddoo...
        ...odrdddrdo....
        ..ooodddddooo...
        .occoooooocco...
        ..oo.....oo.....
        ................
    """, o="#55403e", b="#b69360", h="#ddbe80", s="#8d704f", d="#443843", r="#f5797c", c="#efce91"),
}
