# Copyright 2026 cptntrps
# SPDX-License-Identifier: Apache-2.0

"""16x16 pixel-art sprites for the Baby Size panel app, drawn as text and recoloured per object.

Each shape uses palette letters; each object maps letters to colours. '.' is transparent.
  o outline   b base   h highlight   s shade   l leaf   d detail   t stem
"""

SHAPES = {
    "round": [  # apple, lime, lemon, peach, plum, orange, tomato, kiwi
        "................",
        ".......tl.......",
        "......tlll......",
        ".....ooooooo....",
        "...oobbbbbbboo..",
        "..obhhbbbbbbbso.",
        "..obhbbbbbbbbso.",
        ".obbbbbbbbbbbsso",
        ".obbbbbbbbbbbsso",
        ".obbbbbbbbbbbsso",
        ".obbbbbbbbbbssso",
        "..obbbbbbbbssso.",
        "..obbbbbbbsssso.",
        "...oosssssssoo..",
        ".....ooooooo....",
        "................",
    ],
    "berry": [  # strawberry
        "................",
        ".....l.ll.l.....",
        "....lllllll.....",
        "...oolllllloo...",
        "..obbbbbbbbbbo..",
        ".obhbdbbbdbbbso.",
        ".obhbbbdbbbdbso.",
        ".obbdbbbbdbbbso.",
        "..obbbdbbbbdso..",
        "..obdbbbdbbbso..",
        "...obbbbbdbso...",
        "...obbdbbbsso...",
        "....obbbbsso....",
        ".....obbsso.....",
        "......osso......",
        ".......oo.......",
    ],
    "cluster": [  # grape, blueberry bunch, raspberry
        "................",
        ".......tt.......",
        "......t.ll......",
        "....oo.oo.oo....",
        "...obhobhobho...",
        "...obbobbobbo...",
        "....oo.oo.oo....",
        ".....oo.oo.oo...",
        "....obhobhobho..",
        "....obbobbobbo..",
        ".....oo.oo.oo...",
        "......oo.oo.....",
        ".....obhobho....",
        ".....obbobbo....",
        "......oo.oo.....",
        "................",
    ],
    "drop": [  # pear, avocado, fig
        "................",
        "........t.......",
        ".......tl.......",
        "......oool......",
        ".....obbbo......",
        ".....obhbso.....",
        "....obhbbso.....",
        "....obbbbbso....",
        "...obbbbbbsso...",
        "..obhbbbbbbsso..",
        "..obhbbbbbbbso..",
        "..obbbbbbbbbso..",
        "..obbbbbbbbsso..",
        "...obbbbbbsso...",
        "....oossssoo....",
        "......oooo......",
    ],
    "banana": [
        "................",
        "............tt..",
        "...........obo..",
        "...........obo..",
        "..........obbo..",
        "..........obbo..",
        ".........obbso..",
        "........obbbso..",
        ".......obhbbso..",
        "......obhbbsso..",
        "....oobhbbsso...",
        "..oobhbbbbsso...",
        ".obhbbbbssso....",
        ".obbbbsssoo.....",
        "..ooooooo.......",
        "................",
    ],
    "carrot": [
        "..........l.l...",
        "...........ll.l.",
        "..........llll..",
        ".........ooll...",
        "........obbo....",
        ".......obhbso...",
        "......obhbdso...",
        ".....obhbbso....",
        "....obbbdso.....",
        "...obbbbso......",
        "...obdbbso......",
        "..obbbso........",
        "..obbso.........",
        ".obso...........",
        ".oo.............",
        "................",
    ],
    "corn": [
        "......l.........",
        ".....lo.l.......",
        "....l.oo.l......",
        "...l.obbo.l.....",
        "...l.ohdbo.l....",
        "..l.obdbdbo.l...",
        "..l.ohdbdbo.l...",
        "..l.obdbdbo.l...",
        "..l.ohdbdbo.l...",
        "..l.obdbdbo.l...",
        "...l.obdbo.l....",
        "...l.obdbo.l....",
        "....l.oo.l......",
        ".....llll.......",
        "......ll........",
        "................",
    ],
    "pineapple": [
        "......l.l.......",
        ".....l.ll.l.....",
        "......llll......",
        ".......ll.......",
        ".....oooooo.....",
        "....obdbbdbo....",
        "...obhbdbbdbo...",
        "...obdbbdbbso...",
        "...obbdbbdbso...",
        "...obdbbdbbso...",
        "...obbdbbdbso...",
        "...obdbbdbsso...",
        "....obbdbbso....",
        ".....ossssoo....",
        "......oooo......",
        "................",
    ],
    "melon": [  # watermelon, honeydew, cantaloupe, coconut (via colours)
        "................",
        "................",
        ".....oooooo.....",
        "...oobdbbdboo...",
        "..obhdbbdbbdso..",
        ".obhbdbbdbbdsso.",
        ".obhbdbbdbbdsso.",
        "obbbdbbdbbdbssso",
        "obbbdbbdbbdbssso",
        "obbbdbbdbbdbssso",
        ".obbdbbdbbdbsso.",
        ".obbbdbbdbbssso.",
        "..obbdbbdbssso..",
        "...oosssssssoo..",
        ".....oooooo.....",
        "................",
    ],
    "leafy": [  # lettuce, cabbage, cauliflower, broccoli
        "................",
        "....oo.oo.oo....",
        "...ohbohbohbo...",
        "..obbbobbbobbo..",
        ".ohbbobhbbobbso.",
        ".obbobbbbbobbso.",
        ".obhbbbobbbbsso.",
        "..obbbobbbobso..",
        "...oobbbbbsoo...",
        ".....ollllo.....",
        "....olllllo.....",
        ".....olllo......",
        "......ooo.......",
        "................",
        "................",
        "................",
    ],
    "eggplant": [  # eggplant, butternut, zucchini, squash
        "................",
        "............ll..",
        "...........lllo.",
        "..........ollo..",
        ".........obbo...",
        "........obhbso..",
        ".......obhbbso..",
        "......obhbbsso..",
        ".....obhbbbsso..",
        "....obhbbbbsso..",
        "...obhbbbbbso...",
        "..obbbbbbbsso...",
        "..obbbbbbsso....",
        "...obbbssso.....",
        "....oooooo......",
        "................",
    ],
    "seed": [  # poppy, sesame, lentil, pea, coffee bean, olive, peanut
        "................",
        "................",
        "................",
        "................",
        "................",
        "......oooo......",
        ".....obhbbo.....",
        "....obhbbbso....",
        "....obbbbbso....",
        "....obbbbsso....",
        ".....obsssoo....",
        "......oooo......",
        "................",
        "................",
        "................",
        "................",
    ],
    "ball": [  # tennis ball, baseball, ping pong ball
        "................",
        "................",
        ".....oooooo.....",
        "...oobbbbbboo...",
        "..obhbbbbbdbso..",
        "..obhbbbbdbbso..",
        ".obbbbbbdbbbsso.",
        ".obddbbbdbbbsso.",
        ".obbbddddbbbsso.",
        ".obbbbbbbddbsso.",
        "..obbbbbbbbdso..",
        "..obbbbbbbbsso..",
        "...oossssssoo...",
        ".....oooooo.....",
        "................",
        "................",
    ],
    "bear": [  # teddy bear, rubber duck stays a bear: friendlier on 16 px
        "................",
        "..oo........oo..",
        ".obbo......obbo.",
        ".obdooooooodbo..",
        "..oobbbbbbbboo..",
        "..obbbbbbbbbbo..",
        "..obbobbbbobbo..",
        "..obbbbddbbbbo..",
        "..obbbdddbbbso..",
        "...obbbbbbbso...",
        "..oobbbbbbbsoo..",
        ".obbobbhbbsobbo.",
        ".obboobbbbsobbo.",
        "..oo.obbbso.oo..",
        ".....oo..oo.....",
        "................",
    ],
}

# object id: (shape, {letter: colour})
def _p(base, shade, hi, outline="#1b1f24", leaf="#4caf50", detail=None, stem="#7a5230"):
    return {"o": outline, "b": base, "s": shade, "h": hi, "l": leaf, "d": detail or shade, "t": stem}

OBJECTS = {
    "poppy": ("seed", _p("#5a5a6e", "#3a3a48", "#8a8aa0")),
    "sesame": ("seed", _p("#f1e2b5", "#cdb67e", "#fff6dc")),
    "lentil": ("seed", _p("#e08a3c", "#b0652a", "#f5b47a")),
    "pea": ("seed", _p("#7ccf4a", "#4f9a2c", "#b8f08a")),
    "coffeebean": ("seed", _p("#7a4a2a", "#55311a", "#a8704a")),
    "blueberry": ("cluster", _p("#5b7cff", "#3550c8", "#9fb3ff")),
    "raspberry": ("cluster", _p("#f0386b", "#b81f4c", "#ff8aa8")),
    "olive": ("seed", _p("#8fa83a", "#647a22", "#c2d86a")),
    "grape": ("cluster", _p("#b466e6", "#7c3cb0", "#dcaaff")),
    "cherry": ("round", _p("#e8293a", "#a8141f", "#ff8a8f")),
    "strawberry": ("berry", _p("#f03a3a", "#b81f22", "#ff8f8f", detail="#ffe27a")),
    "walnut": ("round", _p("#c49a6c", "#8d6a42", "#e6c79d", leaf="#c49a6c", stem="#8d6a42")),
    "fig": ("drop", _p("#9b59d0", "#6a3596", "#c79bf0")),
    "pingpong": ("ball", _p("#ffffff", "#c9ced6", "#ffffff", detail="#e9edf2")),
    "lime": ("round", _p("#8ed83c", "#5aa424", "#c8f58a")),
    "plum": ("round", _p("#8e3fb8", "#5f2380", "#c08ae0")),
    "kiwi": ("round", _p("#a07a3c", "#735524", "#c9a46a", leaf="#a07a3c")),
    "egg": ("drop", _p("#fbf3e6", "#d9cdb8", "#ffffff", leaf="#fbf3e6", stem="#fbf3e6")),
    "lemon": ("round", _p("#ffe03a", "#d4b21a", "#fff59a")),
    "tennisball": ("ball", _p("#d6f23a", "#a7c41f", "#efff8a", detail="#ffffff")),
    "peach": ("round", _p("#ffa36b", "#e0703e", "#ffd0a8")),
    "orange": ("round", _p("#ff9a1f", "#d46f0a", "#ffc87a")),
    "baseball": ("ball", _p("#f7f7f2", "#cfcfc6", "#ffffff", detail="#e23a3a")),
    "apple": ("round", _p("#e83a3a", "#a81f22", "#ff9a8f")),
    "avocado": ("drop", _p("#5f9a36", "#3d6a1f", "#9fd06a")),
    "teddy": ("bear", _p("#c98a4a", "#9a6330", "#e6b07a", detail="#5a3a1f")),
    "pear": ("drop", _p("#c4dc4a", "#93a82a", "#e8f58a")),
    "bellpepper": ("round", _p("#f23a2a", "#b81f15", "#ff8f80")),
    "mango": ("drop", _p("#ffb52a", "#e0702a", "#ffe08a", leaf="#4caf50")),
    "banana": ("banana", _p("#ffe03a", "#d4aa1a", "#fff59a", stem="#5a4a1f")),
    "carrot": ("carrot", _p("#ff8a1f", "#d4600a", "#ffbe7a", detail="#d4600a")),
    "papaya": ("drop", _p("#ff9a3a", "#e06a1f", "#ffc88a")),
    "grapefruit": ("round", _p("#ff7a5a", "#d44a32", "#ffb09a")),
    "corn": ("corn", _p("#ffd23a", "#d4a81a", "#fff08a", detail="#e6b81f")),
    "cauliflower": ("leafy", _p("#f4efe2", "#cfc6b0", "#ffffff")),
    "lettuce": ("leafy", _p("#8ed84a", "#5aa42a", "#c8f58a", leaf="#5aa42a")),
    "broccoli": ("leafy", _p("#3fa64a", "#267a30", "#7ad67f", leaf="#8fc46a")),
    "eggplant": ("eggplant", _p("#8e4ac8", "#5f2a8e", "#c08ae8")),
    "butternut": ("eggplant", _p("#f0b45a", "#c88a32", "#ffd89a", leaf="#7a5230")),
    "zucchini": ("eggplant", _p("#4f9a36", "#2f6a1f", "#8fd06a")),
    "cabbage": ("leafy", _p("#a6dc8a", "#74b05a", "#d6f5c4", leaf="#74b05a")),
    "coconut": ("melon", _p("#9a6a3a", "#6a4422", "#c69a6a", detail="#6a4422")),
    "squash": ("round", _p("#ff8a2a", "#d45f12", "#ffbe7a", leaf="#4caf50")),
    "pineapple": ("pineapple", _p("#f5c430", "#c8901a", "#ffe58a", detail="#a8701a")),
    "cantaloupe": ("melon", _p("#e8c48a", "#b89458", "#f8e2b8", detail="#c8a46a")),
    "honeydew": ("melon", _p("#cdeb9a", "#9cc46a", "#ecffc8", detail="#b4d884")),
    "watermelon": ("melon", _p("#3fa64a", "#267a30", "#7ad67f", detail="#1f5a26")),
    "pumpkin": ("melon", _p("#ff8a1f", "#d4600a", "#ffbe7a", detail="#d4600a")),
}


def png_b64(object_id, scale=1):
    """Render one sprite to a base64 PNG (16x16 * scale)."""
    import base64, io
    from PIL import Image
    shape, pal = OBJECTS[object_id]
    rows = SHAPES[shape]
    im = Image.new("RGBA", (16, 16), (0, 0, 0, 0))
    for y, row in enumerate(rows):
        for x, ch in enumerate(row.ljust(16, ".")[:16]):
            if ch != ".":
                c = pal[ch].lstrip("#")
                im.putpixel((x, y), tuple(int(c[i:i + 2], 16) for i in (0, 2, 4)) + (255,))
    if scale > 1:
        im = im.resize((16 * scale, 16 * scale), Image.NEAREST)
    b = io.BytesIO()
    im.save(b, "PNG", optimize=True)
    return base64.b64encode(b.getvalue()).decode()


# ---- characters and funny objects (own shape + palette each) ----
CUSTOM = {
    "gummybear": ([
        "................", "..oo........oo..", ".obbo......obbo.", ".obhboooooobbo..", "..obbbbbbbbbbo..",
        "..obbebbbbebbo..", "..obbbbnnbbbbo..", "...obbbbbbbbo...", "..oobbbbbbbboo..", ".obbobbhbbbobbo.",
        ".obbobbbbbbobbo.", "..oo.obbbbbo.oo.", ".....obbobbo....", ".....oo..oo.....", "................",
        "................"], {"o": "#8a0f1f", "b": "#ff4d6d", "h": "#ffb3c1", "e": "#8a0f1f", "n": "#8a0f1f"}),
    "lego": ([
        "................", "................", "................", "..hh.hh.hh.hh...", "..bb.bb.bb.bb...",
        ".oooooooooooooo.", ".ohbbbbbbbbbbso.", ".ohbbbbbbbbbbso.", ".ohbbbbbbbbbbso.", ".ohbbbbbbbbbbso.",
        ".ohbbbbbbbbbbso.", ".ohbbbbbbbbbbso.", ".ohbbbbbbbbbbso.", ".osssssssssssso.", ".oooooooooooooo.",
        "................"], {"o": "#5a0a0a", "b": "#e3242b", "h": "#ff7a7a", "s": "#a8141a"}),
    "rubberduck": ([
        "................", "....oooo........", "...obbbbo.......", "..obbebbbo......", "..obbbbbbqqo....",
        "...obbbbbqqo....", "....obbbbo......", "..ooobbbbbooo...", ".obbbbbbbbbbbo..", "obhbbbbbbbbbbbo.",
        "obhbbbbbbbbbbso.", "obbbbbbbbbbbsso.", ".obbbbbbbbbsso..", "..oossssssoo....", "....oooooo......",
        "................"], {"o": "#6a4a00", "b": "#ffd93a", "h": "#fff2a0", "s": "#d4a81a", "e": "#1b1f24", "q": "#ff8a1f"}),
    "coxinha": ([
        "................", ".......oo.......", "......obbo......", "......obbo......", ".....obhbbo.....",
        ".....obhbbo.....", "....obhbbbbo....", "....obhbbbbo....", "...obhbbbbbbo...", "...obbbbbbbso...",
        "..obbdbbbdbbso..", "..obbbbdbbbbso..", "..obdbbbbbdsso..", "...osssssssso...", "....oooooooo....",
        "................"], {"o": "#5a3010", "b": "#e8963a", "h": "#ffc070", "s": "#b8661f", "d": "#ffd68a"}),
    "havaianas": ([
        ".....oooooo.....", "....obbbbbbo....", "...obbbwbbbbo...", "...obbwbwbbbo...", "...obwbbbwbbo...",
        "...obwbbbbwbo...", "...obbbbbbbbo...", "....obbbbbbo....", "....obbbbbbo....", "....obbbbbbo....",
        "...obbbbbbbbo...", "...obbbbbbbbo...", "...obbbbbbbbo...", "...obbbggbbbo...", "....obbbbbbo....",
        ".....oooooo....."], {"o": "#0b2a5a", "b": "#2a6be0", "w": "#ffffff", "g": "#3fc24a"}),
    "bowlingpin": ([
        "......oooo......", ".....obhbbo.....", ".....obhbbo.....", "......obbo......", "......orro......",
        "......orro......", ".....obhbbo.....", "....obhbbbbo....", "...obhbbbbbbo...", "...obhbbbbbso...",
        "...obbbbbbbso...", "...obbbbbbsso...", "....obbbbsso....", "....obbbbsso....", ".....oooooo.....",
        "................"], {"o": "#3a3a44", "b": "#f4f4f0", "h": "#ffffff", "s": "#c9c9c0", "r": "#e23a3a"}),
    "spool": ([
        ".....oooooo.....", "...ooffffffoo...", "..offhfffffffo..", ".offhffffffffso.", ".ofhffoooofffso.",
        "ofhffoggggoffsso", "offffogddgoffsso", "offffogddgoffsso", "offffoggggoffsso", ".offffoooofffso.",
        ".offfffffffffso.", "..offffffffsso..", "...ooffffssoo...", ".....oooooo.....", "................",
        "................"], {"o": "#1b1f24", "f": "#2fbf71", "h": "#9ff0c3", "s": "#1f8a50", "g": "#b8bec7", "d": "#4a5058"}),
    "chihuahua": ([
        "................", ".oo.........oo..", ".obo.......obo..", ".obbo.....obbo..", ".obbboooooobbbo.",
        "..obbbbbbbbbbo..", "..obebbbbbbebo..", "..obbbbnnbbbbo..", "...obbbbbbbbo...", "....oobbbboo....",
        "....obbbbbbo....", "...obbbbbbbbo...", "...obboooobbo...", "...obo....obo...", "...oo......oo...",
        "................"], {"o": "#4a3020", "b": "#e0b07a", "e": "#1b1f24", "n": "#1b1f24"}),
    "cat": ([
        "................", "....o.....o.....", "....oo...oo.....", "....obooobo.....", "....obbbbbo.....",
        "....obebebo.....", "....obbnbbo.....", ".....obbbo......", "....obbbbbo.....", "...obbbbbbbo....",
        "...obbbbbbbo..o.", "...obbbbbbbo.obo", "...obbbbbbbo.bo.", "...obbbbbbbobbo.", "....ooooooooo...",
        "................"], {"o": "#5a3010", "b": "#f0a040", "e": "#5fd04a", "n": "#ff8fa0"}),
    # Adapted from Kenney Tiny Dungeon, Tiles/tile_0099.png (CC0): blonde hair,
    # pink bow/top and turquoise skirt. https://kenney.nl/assets/tiny-dungeon
    "pollypocket": ([
        "................",
        "....aaaaaaaa....",
        "...aaaaaaaaaa...",
        "..aaabcdddbaeae.",
        "..aadcdcddddefe.",
        ".aaaddcdddddeae.",
        ".aabdddddccdbaa.",
        ".aadddgcccgcdaa.",
        ".aaddcgcccgchaa.",
        ".aaddcccicccdaa.",
        ".aadddcccccbdaa.",
        "aaacddiiiibecaaa",
        "aacccdeejeecccaa",
        "aaccadkkdkkaccaa",
        "aaaaallllllaaaaa",
        ".aaallllkllaaaa."], {
            "a": "#4b3b59", "b": "#b58235", "c": "#ffe1b1",
            "d": "#f7cf61", "e": "#ff68ad", "f": "#ffbedb",
            "g": "#342e4f", "h": "#ffc18e", "i": "#efa68c",
            "j": "#ffb7d7", "k": "#8af2ed", "l": "#2dbac7",
        }),
    "tamagotchi": ([
        "................", "......oooo......", "....oobbbboo....", "...obbhbbbbbo...", "..obbhbbbbbbbo..",
        "..obbooooooobo..", "..obbowwwwwobo..", "..obbowdwdwobo..", "..obbowwdwwobo..", "..obbooooooobo..",
        "..obbbbbbbbbbo..", "..obbcbbcbbcbo..", "...obbbbbbbbo...", "....oobbbboo....", "......oooo......",
        "................"], {"o": "#2a3a7a", "b": "#6fa8ff", "h": "#cfe2ff", "w": "#c8e6a0", "d": "#2a3a20", "c": "#ffd23a"}),
    "stuart": ([
        "................", "..oo......oo....", ".obpo....opbo...", ".obppoooopbbo...", "..obbbbbbbbo....",
        "..obebbbbebo....", "..obbbbnbbbo....", "...obbbbbbo.....", "....orrrro......", "...orrrrrro.....",
        "..orrrrrrrro....", "...orrrrrro.....", "...obbo.obbo....", "...oo...oo....o.", "................",
        "................"], {"o": "#3a3a44", "b": "#b8b8c4", "p": "#ff9fb4", "e": "#1b1f24", "n": "#ff6f8f", "r": "#e23a3a"}),
    "tinkerbell": ([
        "......oo........", ".....oyyo.......", "....oyyyyo......", "....okkkko......", "ww..okekeo..ww..",
        "www..okkko.www..", ".www..ogo..www..", "..ww.oggggo.ww..", "....ogggggo.....", "...ogggggggo....",
        "..ogggggggggo...", "....ok...ko.....", "....ok...ko.....", "...oo.....oo....", "................",
        "................"], {"o": "#3a3020", "y": "#ffe066", "k": "#ffd8b8", "e": "#1b1f24", "g": "#4ccf5a", "w": "#bfeaff"}),
    "smurf": ([
        ".....oooo.......", "....owwwwoo.....", "...owwwwwwwo....", "..owwwwwwwwwo...", "..obbbbbbbbo....",
        "..obedbbedbo....", "..obbbnnbbbo....", "...obbbbbbo.....", "....obbbbo......", "...obbbbbbo.....",
        "..obbbbbbbbo....", "..owwwwwwwwo....", "..owwwoowwwo....", "..oww....wwo....", "..ooo....ooo....",
        "................"], {"o": "#1b2a5a", "w": "#ffffff", "b": "#3fa0ff", "e": "#ffffff", "d": "#1b1f24", "n": "#2f80e0"}),
    "kirby": ([
        "................", "................", ".....oooooo.....", "...oobbbbbboo...", "..obhbbbbbbbbo..",
        "..obhbbebbebbo..", ".obbbbbebbebbbo.", ".obccbbbbbbccbo.", ".obbbbbmmbbbbbo.", ".obbbbbbbbbbbbo.",
        "..obbbbbbbbbbo..", "..ooobbbbbbooo..", ".orrro....orrro.", ".ooooo....ooooo.", "................",
        "................"], {"o": "#8a2a4a", "b": "#ffa0c8", "h": "#ffd6e8", "e": "#1b2a5a", "c": "#ff6f9f", "m": "#c8285a", "r": "#e8283a"}),
    "babygroot": ([
        "....l....l......", "...lll..lll.....", "....o.oo.o......", "....oooooooo....", "...obbbbbbbbo...",
        "...obedbbedbo...", "...obbbbbbbbo...", "...obbbmmbbbo...", "....obbbbbbo....", ".....obbbbo.....",
        "....obbbbbbo....", "...obobbbbobo...", "...oo.obbo.oo...", "......obbo......", ".....oo..oo.....",
        "................"], {"o": "#3a2410", "b": "#9a6a3a", "l": "#6fcf4a", "e": "#ffffff", "d": "#1b1f24", "m": "#3a2410"}),
    "shelfelf": ([
        ".......oo.......", "......orro......", ".....orrrro.....", "....orrrrrro....", "...owwwwwwwwo...",
        "....okkkkkko....", "....okekkeko....", "....okkmmkko....", ".....okkkko.....", "...owwwwwwwwo...",
        "..orrrrrrrrrro..", "..orrorrrrorro..", "..okkorrrrokko..", ".....orooro.....", "....ooo..ooo....",
        "................"], {"o": "#3a1010", "r": "#e2283a", "w": "#ffffff", "k": "#ffd8b8", "e": "#1b1f24", "m": "#c8285a"}),
    "leprechaun": ([
        "....oooooo......", "....oggggo......", "....oggggo......", "....ozyyzo......", "..oooooooooo....",
        "...okkkkkko.....", "...okekkeko.....", "..oaakkkkaao....", "..oaaakkaaao....", "...oaaaaaao.....",
        "..ogggaagggo.yy.", ".oggggggggggoyyy", "..ogggggggo.oddo", "...ogg.ggo..oddo", "...ooo.ooo...oo.",
        "................"], {"o": "#1b2a10", "g": "#2faa3a", "z": "#1b1f24", "y": "#ffd23a", "k": "#ffd8b8", "e": "#1b1f24", "a": "#ff7a1f", "d": "#2a2a30"}),
    "gnome": ([
        ".......o........", "......oro.......", "......oro.......", ".....orrro......", ".....orrro......",
        "....orrrrro.....", "...orrrrrrro....", "...okkkkkkko....", "...okknnnkko....", "..owwwwwwwwwo...",
        "..owwwwwwwwwo...", "..obwwwwwwwbo...", "..obbwwwwwbbo...", "..obbbwwwbbbo...", "...ooo...ooo....",
        "................"], {"o": "#2a1a10", "r": "#e2283a", "k": "#ffd8b8", "n": "#ff9a8a", "w": "#ffffff", "b": "#3a6fe0"}),
    "pikachu": ([
        ".o..........o...", ".do........od...", ".obo......obo...", "..obo....obo....", "..obboooobbo....",
        ".obbbbbbbbbbo...", ".obebbbbbbebo...", ".orrbbmmbbrro...", ".obbbbbbbbbbo...", "..obbbbbbbbo....",
        "..obbbbbbbbo.oo.", "..obbbbbbbbooboo", "..obbbbbbbbobo..", "...obbbbbbo.o...", "...oo....oo.....",
        "................"], {"o": "#3a2a00", "d": "#1b1f24", "b": "#ffd83a", "e": "#1b1f24", "r": "#ff3a3a", "m": "#8a2a10"}),
    "grogu": ([
        "................", "................", ".....oooooo.....", "oo..obbbbbbo..oo", "obooobbbbbbooobo",
        ".obbbbbbbbbbbbo.", "..obeebbbbeebo..", "...obbbbbbbbo...", "....obbmmbbo....", ".....oooooo.....",
        "....orrrrrro....", "...orrrrrrrro...", "...orrbrrbrro...", "...orrrrrrrro...", "....oooooooo....",
        "................"], {"o": "#2a3a1a", "b": "#8fd06a", "e": "#1b1f24", "m": "#4a6a2a", "r": "#a07a50"}),
    "minion": ([
        ".....oooooo.....", "....obbbbbbo....", "...obbbbbbbbo...", "...oggggggggo...", "...oggwddwggo...",
        "...oggwwwwggo...", "...obbbbbbbbo...", "...obbbmmbbbo...", "...obbbbbbbbo...", "...ouuuuuuuuo...",
        "..obuuuuuuuubo..", "...ouuuuuuuuo...", "...ouuuuuuuuo...", "....ooo..ooo....", "....odo..odo....",
        "....ooo..ooo...."], {"o": "#2a2a30", "b": "#ffd83a", "g": "#4a4a55", "w": "#e8e8f0", "d": "#6a4a20", "m": "#6a2a10", "u": "#2f6fd0"}),
    "jigglypuff": ([
        "..oo.......oo...", ".obbo.ooo.obbo..", ".obboobbboobbo..", "..obbbbcbbbbbo..", ".obbbbbbcbbbbbo.",
        ".obeebbbbbeebbo.", ".obeddbbbeddbbo.", ".obeebbbbbeebbo.", ".obbbbbmmbbbbbo.", ".obbbbbbbbbbbbo.",
        "..obbbbbbbbbbo..", "...oobbbbbboo...", ".....oooooo.....", "....oo....oo....", "................",
        "................"], {"o": "#8a2a5a", "b": "#ffb0d0", "c": "#ff8fc0", "e": "#4ab0ff", "d": "#1b2a5a", "m": "#c8285a"}),
}
from pokemon import SPRITES as POKEMON_SPRITES

CUSTOM.update(POKEMON_SPRITES)
for _k, (_rows, _pal) in CUSTOM.items():
    SHAPES["c_" + _k] = _rows
    OBJECTS[_k] = ("c_" + _k, _pal)
for _n in ("spool1", "spool2", "spool3"):
    OBJECTS[_n] = OBJECTS["spool"]
OBJECTS["gummybear"] = ("bear", {"o": "#8a0f1f", "b": "#ff4d6d", "h": "#ffb3c1", "s": "#d42a4a", "d": "#8a0f1f"})
