---
id: grafana
name: Grafana
summary: Display Grafana Metrics
desc: Show value or graph of Grafana metrics.
author: tavdog
fileName: grafana.star
packageName: grafana
category: utilities
tags:
- tech
- data-visual
- utility
published: '2025-11-21T09:42:57Z'
updated: '2026-04-02T20:26:05Z'
